name: Move Folder from Second Repo

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  move-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge Second Repo
      run: |
        git remote add [-f] second_repo url.https://${{ secrets.OTHER_TOKEN }}@github.com/.insteadOf https://github.com/
        git fetch second_repo
        git merge second_repo/main --allow-unrelated-histories
        git push origin main

    #- name: Move Folder to Another Branch
      #run: |
        #git checkout -b new_Branch
        #git mv <folder_name> <destination_path>
        #git commit -am "Move folder to new branch"
        #git push origin <new_branch_name>
