name: Move Folders and Files

on:
  push:
    branches:
      - main

jobs:
  move_folders_and_files:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Other Repository
      uses: actions/checkout@v2
      with:
        repository: matze240/Other_repo
        ref: main

    - name: Fetch Files Folder
      run: |
        mkdir -p external_files
        cp -r files external_files

    - name: Checkout Main Branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Move Data Folder to New Branch
      run: |
        git checkout -b new_Branch
        mv main/data .

    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Move data folder to new_Branch and add files folder"
        git push origin new_Branch
