name: Move Folder to Another Branch

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on in the first repository

jobs:
  move_folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout First Repository
      uses: actions/checkout@v2
      with:
        repository: matze2402/my_repo-1-
        ref: main

    - name: Clone Second Repository
      run: |
        git clone --filter=blob:none --no-checkout https://github.com/matze240/other_repo.git
        cd other_repo
        git config core.sparseCheckout true
        echo "./files/*" >> .git/info/sparse-checkout
        git checkout

    - name: Fetch Contents from First Repository
      run: |
        cd other_repo
        git fetch origin main

    - name: Move Folder
      run: |
        mv ./main/files ../my_repo-1-/
        cd ../my_repo-1-/
        git checkout -b new_Branch # Change this to the desired branch name
        git add .
        git commit -m "Move folder from main branch"
        git push origin new_Branch

    - name: Cleanup
      run: rm -rf second-repo
