name: Move Folder to Another Branch

on:
  push:
    branches:
      - main

jobs:
  move_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout First Repository
        uses: actions/checkout@v2

      - name: Checkout Second Repository
        run: git clone https://github.com/matze240/other_repo.git second_repository

      - name: Move Folder and Ignore Workflow File
        run: |
          cd second_repository
          git config user.email "your_email@example.com"
          git config user.name "matze2402"
          git checkout -b new_branch
          git mv files/* .
          git commit -m "Move folder to new branch, ignoring workflow file"
          git push origin new_branch
