name: Move Folder to Another Branch

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on in the first repository

jobs:
  move_folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout First Repository
      uses: actions/checkout@v2
      with:
        repository: matze2402/my_repo-1-
        ref: main

    - name: Clone Second Repository
      run: git clone --depth 1 https://github.com/matze240/other_repo.git

    - name: Fetch Contents from First Repository
      run: |
        cd other_repo
        git fetch origin main

    - name: Move Folder
      run: |
        mv ./files ../other_repo/
        cd ../my_repo-1-/
        git checkout -b new-branch-name  # Change this to the desired branch name
        git add .
        git commit -m "Move folder from main branch"
        git push origin new_Branch

    - name: Cleanup
      run: rm -rf second-repo
